CREATE TABLE ORDER_ADM.SHEDLOCK (
    NAME                           VARCHAR2(64)    NOT NULL,
    LOCK_UNTIL                     TIMESTAMP       NOT NULL,
    LOCKED_AT                      TIMESTAMP       NOT NULL,
    LOCKED_BY                      VARCHAR2(255)   NOT NULL
  ) TABLESPACE TSDORDER01 INITRANS 2;

CREATE PUBLIC SYNONYM SHEDLOCK FOR ORDER_ADM.SHEDLOCK;

ALTER TABLE ORDER_ADM.SHEDLOCK
    ADD CONSTRAINT SHEDLOCK_PK PRIMARY KEY (NAME) USING INDEX INITRANS 2 TABLESPACE TSDORDER01;

GRANT SELECT, INSERT, UPDATE ON ORDER_ADM.SHEDLOCK                       TO ORDERUBR;
GRANT READ                   ON ORDER_ADM.SHEDLOCK                       TO RL_COMPLIANCE_NSA;