CREATE TABLE ORDER_ADM.ORDERS (
    IDT_ORDER         VARCHAR2(40) PRIMARY KEY,
    IDT_CLIENT        VARCHAR2(40) NOT NULL,
    NUM_TOTAL_AMOUNT  DECIMAL(18,2) DEFAULT 0 NOT NULL,
    DAT_ORDER         TIMESTAMP    NOT NULL,
    DAT_CREATION      TIMESTAMP    NOT NULL,
    DAT_UPDATE        TIMESTAMP    NOT NULL
) TABLESPACE TSDORDER01 INITRANS 2;

CREATE TABLE ORDER_ADM.ITEM_ORDER (
    IDT_ITEM_ORDER   NUMBER(18,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDT_ITEM         VARCHAR2(40) NOT NULL,
    IDT_ORDER        VARCHAR2(40) NOT NULL,
    NUM_AMOUNT       DECIMAL(18,2) NOT NULL,
    NUM_QTDE         NUMBER(18,0)  NOT NULL,
    NUM_TOTAL_AMOUNT DECIMAL(18,2) NOT NULL,
    FOREIGN KEY (IDT_ORDER) REFERENCES ORDER_ADM.ORDERS(IDT_ORDER) ON DELETE CASCADE
) TABLESPACE TSDORDER01 INITRANS 2;

CREATE PUBLIC SYNONYM ORDERS FOR ORDER_ADM.ORDERS;
CREATE PUBLIC SYNONYM ITEM_ORDER FOR ORDER_ADM.ITEM_ORDER;

GRANT SELECT, INSERT, UPDATE ON ORDER_ADM.ORDERS                         TO ORDERUBR;
GRANT SELECT, INSERT, UPDATE ON ORDER_ADM.ITEM_ORDER                     TO ORDERUBR;

GRANT READ                   ON ORDER_ADM.ORDERS                         TO RL_COMPLIANCE_NSA;
GRANT READ                   ON ORDER_ADM.ITEM_ORDER                     TO RL_COMPLIANCE_NSA;