ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE TSDORDER01 LOGGING DATAFILE 'TSDORDER01.dbf' SIZE 512m AUTOEXTEND ON NEXT 512m EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE TSIORDER01 LOGGING DATAFILE 'TSIORDER01.dbf' SIZE 512m AUTOEXTEND ON NEXT 512m EXTENT MANAGEMENT LOCAL;
CREATE TABLESPACE TSLORDER01 LOGGING DATAFILE 'TSLORDER01.dbf' SIZE 512m AUTOEXTEND ON NEXT 512m EXTENT MANAGEMENT LOCAL;

CREATE USER ORDER_ADM IDENTIFIED BY ORDER_ADM;
CREATE USER ORDERUBR IDENTIFIED BY ORDERUBR;

GRANT CONNECT, RESOURCE, CREATE PUBLIC SYNONYM TO ORDERUBR;
GRANT CONNECT TO ORDERUBR;
GRANT CONNECT, RESOURCE, CREATE PUBLIC SYNONYM TO ORDER_ADM;
GRANT CONNECT TO ORDER_ADM;

GRANT DROP ANY TABLE TO ORDER_ADM;
GRANT DROP ANY SYNONYM TO ORDER_ADM;
GRANT DROP PUBLIC SYNONYM TO ORDER_ADM;
GRANT DROP ANY SEQUENCE TO ORDER_ADM;

CREATE ROLE RL_COMPLIANCE_NSA;
CREATE ROLE RL_AD;

ALTER USER ORDER_ADM quota unlimited on TSDORDER01;
ALTER USER ORDER_ADM quota unlimited on TSIORDER01;
ALTER USER ORDER_ADM quota unlimited on USERS;